Use step output to control uploading of DEPENDENCIES file

diff --git a/.github/workflows/check-dependencies.yaml b/.github/workflows/check-dependencies.yaml
--- a/.github/workflows/check-dependencies.yaml
+++ b/.github/workflows/check-dependencies.yaml
@@ -38,7 +38,7 @@ jobs:
         cargo tree -e normal --prefix none --no-dedupe \
           | sort -u \
           | grep -v '^[[:space:]]*$' \
-          | grep -v uprotocol-sdk \
+          | grep -v up-rust \
           | sed -E 's|([^ ]+) v([^ ]+).*|crate/cratesio/-/\1/\2|' \
           > DEPS.txt
     - name: Set up JDK
@@ -46,18 +46,28 @@ jobs:
       with:
         distribution: "temurin"
         java-version: "17"
-    - name: "Download latest Dash jar file"
-      working-directory: ${{github.workspace}}
-      run: |
-        wget -O dash.jar "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"
     - name: "Run latest Eclipse Dash jar file"
+      id: "run-checks"
       working-directory: ${{github.workspace}}
-      continue-on-error: true
       run: |
-        wget -O dash.jar "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"
-        java -Dorg.eclipse.dash.timeout=60 -jar dash.jar -batch 90 -summary DEPENDENCIES.txt DEPS.txt
+        wget --quiet -O dash.jar "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"
+        if java -Dorg.eclipse.dash.timeout=60 -jar dash.jar -batch 90 -summary DEPENDENCIES.txt DEPS.txt
+        then
+          echo "checks-failed=0" >> $GITHUB_OUTPUT
+          echo "License information of 3rd party dependencies has been vetted successfully." >> $GITHUB_STEP_SUMMARY
+        else
+          echo "checks-failed=1" >> $GITHUB_OUTPUT
+          echo "License information of some 3rd party dependencies could not be vetted successfully." >> $GITHUB_STEP_SUMMARY
+          echo "A DEPENDENCIES file containing the vetted information has been attached to this workflow run." >> $GITHUB_STEP_SUMMARY
+        fi
     - name: Upload DEPENDENCIES file
+      if: ${{ steps.run-checks.outputs.checks-failed == '1' }}
       uses: actions/upload-artifact@v4
       with:
         name: 3rd-party-dependencies
         path: DEPENDENCIES.txt
+    - name: "Determine exit code"
+      env:
+        EXIT_CODE: ${{ steps.run-checks.outputs.checks-failed }}
+      run: |
+        exit $EXIT_CODE
